INSERT INTO public.league VALUES (10175, 'Super Cup', 'Albania');
INSERT INTO public.league VALUES (260, 'Superiore', 'Albania');
INSERT INTO public.league VALUES (9173, 'Superiore Qualification', 'Albania');
INSERT INTO public.league VALUES (516, 'Ligue 1', 'Algeria');
INSERT INTO public.league VALUES (112, 'Liga Profesional', 'Argentina');
INSERT INTO public.league VALUES (8965, 'Primera B Nacional', 'Argentina');
INSERT INTO public.league VALUES (9213, 'Primera B Metropolitana & Torneo Federal A', 'Argentina');
INSERT INTO public.league VALUES (9305, 'Copa Argentina', 'Argentina');
INSERT INTO public.league VALUES (9381, 'Super Cup', 'Argentina');
INSERT INTO public.league VALUES (9170, 'Argentina Promotion/Relegation', 'Argentina');
INSERT INTO public.league VALUES (10007, 'Copa de la Liga Profesional', 'Argentina');
INSERT INTO public.league VALUES (10075, 'Torneo de Verano', 'Argentina');
INSERT INTO public.league VALUES (10053, 'Trofeo de Campeones', 'Argentina');
INSERT INTO public.league VALUES (118, 'Premier League', 'Armenia');
INSERT INTO public.league VALUES (113, 'A-League', 'Australia');
INSERT INTO public.league VALUES (9495, 'A-League Women', 'Australia');
INSERT INTO public.league VALUES (9471, 'Australia Cup', 'Australia');
INSERT INTO public.league VALUES (38, 'Bundesliga', 'Austria');
INSERT INTO public.league VALUES (119, '2. Liga', 'Austria');
INSERT INTO public.league VALUES (278, 'Austrian Cup', 'Austria');
INSERT INTO public.league VALUES (262, 'Premier League', 'Azerbaijan');
INSERT INTO public.league VALUES (10443, 'Premier League', 'Bangladesh');
INSERT INTO public.league VALUES (263, 'Premier Division', 'Belarus');
INSERT INTO public.league VALUES (9255, 'Premier League qualification', 'Belarus');
INSERT INTO public.league VALUES (9521, 'Belarusian Cup', 'Belarus');
INSERT INTO public.league VALUES (9658, 'Super Cup', 'Belarus');
INSERT INTO public.league VALUES (40, 'First Division A', 'Belgium');
INSERT INTO public.league VALUES (264, '2. Division', 'Belgium');
INSERT INTO public.league VALUES (149, 'Belgian Cup', 'Belgium');
INSERT INTO public.league VALUES (41, 'First Division A Qualification', 'Belgium');
INSERT INTO public.league VALUES (266, 'Super Cup', 'Belgium');
INSERT INTO public.league VALUES (144, 'Primera Division', 'Bolivia');
INSERT INTO public.league VALUES (9334, 'Primera Division Qualification', 'Bolivia');
INSERT INTO public.league VALUES (267, 'Premier League', 'Bosnia-Herzegovina');
INSERT INTO public.league VALUES (268, 'Serie A', 'Brazil');
INSERT INTO public.league VALUES (8814, 'Serie B', 'Brazil');
INSERT INTO public.league VALUES (8971, 'Serie C', 'Brazil');
INSERT INTO public.league VALUES (9067, 'Copa do Brasil', 'Brazil');
INSERT INTO public.league VALUES (9429, 'Copa do Nordeste', 'Brazil');
INSERT INTO public.league VALUES (10077, 'Supercopa do Brasil', 'Brazil');
INSERT INTO public.league VALUES (10290, 'Baiano', 'Brazil');
INSERT INTO public.league VALUES (10272, 'Carioca', 'Brazil');
INSERT INTO public.league VALUES (10274, 'Gaúcho', 'Brazil');
INSERT INTO public.league VALUES (10291, 'Goiano', 'Brazil');
INSERT INTO public.league VALUES (10273, 'Mineiro', 'Brazil');
INSERT INTO public.league VALUES (10244, 'Paulista A1', 'Brazil');
INSERT INTO public.league VALUES (10078, 'Recopa Gaúcha', 'Brazil');
INSERT INTO public.league VALUES (270, 'First Professional League', 'Bulgaria');
INSERT INTO public.league VALUES (271, 'Bulgarian Cup', 'Bulgaria');
INSERT INTO public.league VALUES (9584, 'First professional league Qualification', 'Bulgaria');
INSERT INTO public.league VALUES (9096, 'Second Professional League', 'Bulgaria');
INSERT INTO public.league VALUES (272, 'Super Cup', 'Bulgaria');
INSERT INTO public.league VALUES (9986, 'Premier League', 'Canada');
INSERT INTO public.league VALUES (9837, 'Canadian Championship', 'Canada');
INSERT INTO public.league VALUES (273, 'Primera Division', 'Chile');
INSERT INTO public.league VALUES (9091, 'Copa Chile', 'Chile');
INSERT INTO public.league VALUES (9126, 'Primera B', 'Chile');
INSERT INTO public.league VALUES (9761, 'Primera Division Qualification', 'Chile');
INSERT INTO public.league VALUES (9407, 'Super Cup', 'Chile');
INSERT INTO public.league VALUES (120, 'Super League', 'China');
INSERT INTO public.league VALUES (9137, 'China League', 'China');
INSERT INTO public.league VALUES (9550, 'Chinese FA Cup', 'China');
INSERT INTO public.league VALUES (9491, 'Super Cup', 'China');
INSERT INTO public.league VALUES (10183, 'Super League Qualification', 'China');
INSERT INTO public.league VALUES (9490, 'Copa Colombia', 'Colombia');
INSERT INTO public.league VALUES (274, 'Primera A', 'Colombia');
INSERT INTO public.league VALUES (9125, 'Primera B', 'Colombia');
INSERT INTO public.league VALUES (121, 'Primera Division', 'Costa Rica');
INSERT INTO public.league VALUES (10223, 'Super cup', 'Costa Rica');
INSERT INTO public.league VALUES (252, '1. Division', 'Croatia');
INSERT INTO public.league VALUES (275, 'FA Cup', 'Croatia');
INSERT INTO public.league VALUES (276, 'Super Cup', 'Croatia');
INSERT INTO public.league VALUES (136, '1. Division', 'Cyprus');
INSERT INTO public.league VALUES (9100, '2. Division', 'Cyprus');
INSERT INTO public.league VALUES (330, 'Cyprus Cup ', 'Cyprus');
INSERT INTO public.league VALUES (521, 'Super Cup', 'Cyprus');
INSERT INTO public.league VALUES (122, '1. Liga', 'Czechia');
INSERT INTO public.league VALUES (10025, '1. Liga qualification', 'Czechia');
INSERT INTO public.league VALUES (254, 'Czech Cup', 'Czechia');
INSERT INTO public.league VALUES (253, 'Czech Republic 2', 'Czechia');
INSERT INTO public.league VALUES (46, 'Superligaen', 'Denmark');
INSERT INTO public.league VALUES (85, '1. Division', 'Denmark');
INSERT INTO public.league VALUES (239, '2. Division', 'Denmark');
INSERT INTO public.league VALUES (240, '3. Division', 'Denmark');
INSERT INTO public.league VALUES (241, 'Danmarksserien', 'Denmark');
INSERT INTO public.league VALUES (242, 'DBU Pokalen', 'Denmark');
INSERT INTO public.league VALUES (256, 'Kvindeligaen', 'Denmark');
INSERT INTO public.league VALUES (10046, 'Copa Ecuador', 'Ecuador');
INSERT INTO public.league VALUES (246, 'Serie A', 'Ecuador');
INSERT INTO public.league VALUES (519, 'Premier League', 'Egypt');
INSERT INTO public.league VALUES (9941, 'Egypt Cup', 'Egypt');
INSERT INTO public.league VALUES (10270, 'League Cup', 'Egypt');
INSERT INTO public.league VALUES (10314, 'Super Cup', 'Egypt');
INSERT INTO public.league VALUES (335, 'Primera Division', 'El Salvador');
INSERT INTO public.league VALUES (47, 'Premier League', 'England');
INSERT INTO public.league VALUES (48, 'Championship', 'England');
INSERT INTO public.league VALUES (108, 'League One', 'England');
INSERT INTO public.league VALUES (109, 'League Two', 'England');
INSERT INTO public.league VALUES (117, 'National League', 'England');
INSERT INTO public.league VALUES (8944, 'National North & South', 'England');
INSERT INTO public.league VALUES (8947, 'Premier Division', 'England');
INSERT INTO public.league VALUES (9084, 'Premier League 2 Div 1', 'England');
INSERT INTO public.league VALUES (10176, 'Premier League 2 Div 2', 'England');
INSERT INTO public.league VALUES (247, 'Community Shield', 'England');
INSERT INTO public.league VALUES (132, 'FA Cup', 'England');
INSERT INTO public.league VALUES (133, 'EFL Cup', 'England');
INSERT INTO public.league VALUES (10626, 'FA Cup Qualification', 'England');
INSERT INTO public.league VALUES (142, 'EFL Trophy', 'England');
INSERT INTO public.league VALUES (9253, 'FA Trophy', 'England');
INSERT INTO public.league VALUES (10068, 'Premier League U18', 'England');
INSERT INTO public.league VALUES (9227, 'WSL', 'England');
INSERT INTO public.league VALUES (10082, 'FA Cup (Women)', 'England');
INSERT INTO public.league VALUES (9717, 'Women''s League Cup', 'England');
INSERT INTO public.league VALUES (9294, 'Women''s Championship', 'England');
INSERT INTO public.league VALUES (10705, 'National League Cup', 'England');
INSERT INTO public.league VALUES (248, 'Meistriliiga', 'Estonia');
INSERT INTO public.league VALUES (10034, 'Meistrilia Qualification', 'Estonia');
INSERT INTO public.league VALUES (9069, 'Super Cup', 'Estonia');
INSERT INTO public.league VALUES (9523, 'Løgmanssteypið', 'Faroe Islands');
INSERT INTO public.league VALUES (250, 'Premier League', 'Faroe Islands');
INSERT INTO public.league VALUES (51, 'Veikkausliiga', 'Finland');
INSERT INTO public.league VALUES (52, 'Finland Promotion/Relegation', 'Finland');
INSERT INTO public.league VALUES (251, 'Ykkosliiga', 'Finland');
INSERT INTO public.league VALUES (143, 'Suomen Cup', 'Finland');
INSERT INTO public.league VALUES (8969, 'Kakkonen', 'Finland');
INSERT INTO public.league VALUES (10174, 'Kansallinen (Women)', 'Finland');
INSERT INTO public.league VALUES (10186, 'Kansallinen Qualification (Women)', 'Finland');
INSERT INTO public.league VALUES (342, 'Finland Cup', 'Finland');
INSERT INTO public.league VALUES (10713, 'Ykkosliiga Qualification', 'Finland');
INSERT INTO public.league VALUES (53, 'Ligue 1', 'France');
INSERT INTO public.league VALUES (110, 'Ligue 2', 'France');
INSERT INTO public.league VALUES (8970, 'National', 'France');
INSERT INTO public.league VALUES (134, 'Coupe de France', 'France');
INSERT INTO public.league VALUES (9677, 'Division 1 (W)', 'France');
INSERT INTO public.league VALUES (9666, 'Ligue 1 Qualification', 'France');
INSERT INTO public.league VALUES (9667, 'Ligue 2 Qualification', 'France');
INSERT INTO public.league VALUES (207, 'Super Cup', 'France');
INSERT INTO public.league VALUES (439, 'Erovnuli', 'Georgia');
INSERT INTO public.league VALUES (9310, 'Erovnuli Qualification', 'Georgia');
INSERT INTO public.league VALUES (54, 'Bundesliga', 'Germany');
INSERT INTO public.league VALUES (146, '2. Bundesliga', 'Germany');
INSERT INTO public.league VALUES (208, '3. Liga', 'Germany');
INSERT INTO public.league VALUES (209, 'DFB Pokal', 'Germany');
INSERT INTO public.league VALUES (512, 'Regionalliga', 'Germany');
INSERT INTO public.league VALUES (9081, 'Bundesliga Qualification', 'Germany');
INSERT INTO public.league VALUES (9734, '2. Bundesliga Qualification', 'Germany');
INSERT INTO public.league VALUES (10022, 'Regionella Qualification', 'Germany');
INSERT INTO public.league VALUES (8924, 'Super Cup', 'Germany');
INSERT INTO public.league VALUES (9676, 'Frauen Bundesliga', 'Germany');
INSERT INTO public.league VALUES (10650, 'DFB Pokal Frauen', 'Germany');
INSERT INTO public.league VALUES (522, 'Premier League', 'Ghana');
INSERT INTO public.league VALUES (135, 'Super League 1', 'Greece');
INSERT INTO public.league VALUES (145, 'Greece Cup', 'Greece');
INSERT INTO public.league VALUES (8815, 'Super League 2', 'Greece');
INSERT INTO public.league VALUES (10019, 'Super League Qualification', 'Greece');
INSERT INTO public.league VALUES (336, 'Liga Nacional', 'Guatemala');
INSERT INTO public.league VALUES (337, 'Liga Nacional', 'Honduras');
INSERT INTO public.league VALUES (212, 'NB I', 'Hungary');
INSERT INTO public.league VALUES (213, 'FA Cup', 'Hungary');
INSERT INTO public.league VALUES (215, 'Besta deildin', 'Iceland');
INSERT INTO public.league VALUES (216, '1. Deild', 'Iceland');
INSERT INTO public.league VALUES (217, 'Icelandic Cup', 'Iceland');
INSERT INTO public.league VALUES (10009, 'Super Cup', 'Iceland');
INSERT INTO public.league VALUES (10226, '2. Deild', 'Iceland');
INSERT INTO public.league VALUES (10076, 'League Cup', 'Iceland');
INSERT INTO public.league VALUES (9478, 'Super League', 'India');
INSERT INTO public.league VALUES (10309, 'Durand Cup', 'India');
INSERT INTO public.league VALUES (8982, 'I League', 'India');
INSERT INTO public.league VALUES (10366, 'Super Cup', 'India');
INSERT INTO public.league VALUES (8983, 'Liga 1', 'Indonesia');
INSERT INTO public.league VALUES (523, 'Persian Gulf', 'Iran');
INSERT INTO public.league VALUES (9372, 'Azadegan', 'Iran');
INSERT INTO public.league VALUES (9487, 'Hazfi cup', 'Iran');
INSERT INTO public.league VALUES (10288, 'Super Cup', 'Iran');
INSERT INTO public.league VALUES (524, 'Stars League', 'Iraq');
INSERT INTO public.league VALUES (10310, 'Stars League Relegation Playoff', 'Iraq');
INSERT INTO public.league VALUES (126, 'Premier Division', 'Ireland');
INSERT INTO public.league VALUES (221, 'Premier Division Qualification', 'Ireland');
INSERT INTO public.league VALUES (218, 'First Division', 'Ireland');
INSERT INTO public.league VALUES (219, 'FAI Cup', 'Ireland');
INSERT INTO public.league VALUES (10307, 'FAI Women''s Cup (W)', 'Ireland');
INSERT INTO public.league VALUES (9431, 'Super Cup', 'Ireland');
INSERT INTO public.league VALUES (10210, 'Women''s Premier Division', 'Ireland');
INSERT INTO public.league VALUES (127, 'Ligat HaAl', 'Israel');
INSERT INTO public.league VALUES (128, 'Leumit League', 'Israel');
INSERT INTO public.league VALUES (9735, 'Leumit League Qualification', 'Israel');
INSERT INTO public.league VALUES (9097, 'State Cup', 'Israel');
INSERT INTO public.league VALUES (9862, 'Super Cup', 'Israel');
INSERT INTO public.league VALUES (9098, 'Toto cup', 'Israel');
INSERT INTO public.league VALUES (55, 'Serie A', 'Italy');
INSERT INTO public.league VALUES (86, 'Serie B', 'Italy');
INSERT INTO public.league VALUES (141, 'Coppa Italia', 'Italy');
INSERT INTO public.league VALUES (147, 'Serie C', 'Italy');
INSERT INTO public.league VALUES (222, 'Supercoppa', 'Italy');
INSERT INTO public.league VALUES (10178, 'Serie A Femminile', 'Italy');
INSERT INTO public.league VALUES (10434, 'Serie A Femminile Qualification', 'Italy');
INSERT INTO public.league VALUES (223, 'J. League', 'Japan');
INSERT INTO public.league VALUES (8974, 'J. League 2', 'Japan');
INSERT INTO public.league VALUES (9136, 'J. League 3', 'Japan');
INSERT INTO public.league VALUES (9915, 'J. League Qualification', 'Japan');
INSERT INTO public.league VALUES (9011, 'Emperor Cup', 'Japan');
INSERT INTO public.league VALUES (224, 'J. League Cup', 'Japan');
INSERT INTO public.league VALUES (440, 'Super Cup', 'Japan');
INSERT INTO public.league VALUES (225, 'Premier League', 'Kazakhstan');
INSERT INTO public.league VALUES (9504, 'Super Cup', 'Kazakhstan');
INSERT INTO public.league VALUES (529, 'Premier League', 'Kuwait');
INSERT INTO public.league VALUES (226, 'Virsliga', 'Latvia');
INSERT INTO public.league VALUES (9486, 'Super Cup', 'Latvia');
INSERT INTO public.league VALUES (228, 'A Lyga', 'Lithuania');
INSERT INTO public.league VALUES (9632, 'A Lyga Qualification', 'Lithuania');
INSERT INTO public.league VALUES (9493, 'Super Cup', 'Lithuania');
INSERT INTO public.league VALUES (229, 'National Division', 'Luxembourg');
INSERT INTO public.league VALUES (9527, 'Coupe de Luxembourg', 'Luxembourg');
INSERT INTO public.league VALUES (9174, 'National Division Qualification', 'Luxembourg');
INSERT INTO public.league VALUES (249, 'Prva Liga', 'North Macedonia');
INSERT INTO public.league VALUES (9528, 'Macedonian Cup', 'North Macedonia');
INSERT INTO public.league VALUES (8985, 'Liga Super', 'Malaysia');
INSERT INTO public.league VALUES (230, 'Liga MX', 'Mexico');
INSERT INTO public.league VALUES (8976, 'Liga de Expansión MX', 'Mexico');
INSERT INTO public.league VALUES (9906, 'Liga MX Femenil', 'Mexico');
INSERT INTO public.league VALUES (10325, 'Preseason', 'Mexico');
INSERT INTO public.league VALUES (231, 'National Division', 'Moldova');
INSERT INTO public.league VALUES (9530, 'Cupa Moldova', 'Moldova');
INSERT INTO public.league VALUES (10065, 'National Division Qualification', 'Moldova');
INSERT INTO public.league VALUES (232, '1. CFL', 'Montenegro');
INSERT INTO public.league VALUES (9178, '1. CFL Qualification', 'Montenegro');
INSERT INTO public.league VALUES (530, 'Botola Pro', 'Morocco');
INSERT INTO public.league VALUES (57, 'Eredivisie', 'Netherlands');
INSERT INTO public.league VALUES (111, 'Eerste Divisie', 'Netherlands');
INSERT INTO public.league VALUES (9195, 'Tweede Divisie', 'Netherlands');
INSERT INTO public.league VALUES (58, 'Eredivisie Qualification', 'Netherlands');
INSERT INTO public.league VALUES (10289, 'Eredivisie Vrouwen', 'Netherlands');
INSERT INTO public.league VALUES (235, 'KNVB Cup', 'Netherlands');
INSERT INTO public.league VALUES (237, 'Super Cup', 'Netherlands');
INSERT INTO public.league VALUES (9851, 'Tweede Divisie Qualification', 'Netherlands');
INSERT INTO public.league VALUES (8870, 'Championship', 'New Zealand');
INSERT INTO public.league VALUES (533, 'Professional Football League', 'Nigeria');
INSERT INTO public.league VALUES (129, 'Premiership', 'Northern Ireland');
INSERT INTO public.league VALUES (9389, 'Irish Cup', 'Northern Ireland');
INSERT INTO public.league VALUES (8978, 'League Cup', 'Northern Ireland');
INSERT INTO public.league VALUES (8979, 'Premiership Qualification', 'Northern Ireland');
INSERT INTO public.league VALUES (59, 'Eliteserien', 'Norway');
INSERT INTO public.league VALUES (203, 'OBOS-ligaen', 'Norway');
INSERT INTO public.league VALUES (204, 'PostNord-ligaen', 'Norway');
INSERT INTO public.league VALUES (331, 'Toppserien', 'Norway');
INSERT INTO public.league VALUES (332, '1. Division Kvinner', 'Norway');
INSERT INTO public.league VALUES (10714, '1. Division Qualification', 'Norway');
INSERT INTO public.league VALUES (333, 'Cup (Women)', 'Norway');
INSERT INTO public.league VALUES (10628, 'Cup Qualification', 'Norway');
INSERT INTO public.league VALUES (60, 'Eliteserien Qualification', 'Norway');
INSERT INTO public.league VALUES (206, 'Norgesmesterskapet', 'Norway');
INSERT INTO public.league VALUES (205, 'Norsk Tipping-ligaen', 'Norway');
INSERT INTO public.league VALUES (9754, 'OBOS-ligaen Qualification', 'Norway');
INSERT INTO public.league VALUES (9382, 'Toppserien Qualification (W)', 'Norway');
INSERT INTO public.league VALUES (9039, 'LPF', 'Panama');
INSERT INTO public.league VALUES (10230, 'Copa Paraguay', 'Paraguay');
INSERT INTO public.league VALUES (199, 'Division Profesional', 'Paraguay');
INSERT INTO public.league VALUES (10259, 'Supercopa', 'Paraguay');
INSERT INTO public.league VALUES (131, 'Primera Division', 'Peru');
INSERT INTO public.league VALUES (196, 'Ekstraklasa', 'Poland');
INSERT INTO public.league VALUES (197, '1 Liga', 'Poland');
INSERT INTO public.league VALUES (198, 'Puchar Polski', 'Poland');
INSERT INTO public.league VALUES (200, 'Superpuchar Polski', 'Poland');
INSERT INTO public.league VALUES (8935, '2. Division', 'Poland');
INSERT INTO public.league VALUES (61, 'Liga Portugal', 'Portugal');
INSERT INTO public.league VALUES (185, 'Liga Portugal 2', 'Portugal');
INSERT INTO public.league VALUES (187, 'League Cup', 'Portugal');
INSERT INTO public.league VALUES (9112, 'Liga 3', 'Portugal');
INSERT INTO public.league VALUES (9668, 'Liga Portugal 2 Qualification', 'Portugal');
INSERT INTO public.league VALUES (10215, 'Liga Portugal Qualification', 'Portugal');
INSERT INTO public.league VALUES (186, 'Portugal Cup', 'Portugal');
INSERT INTO public.league VALUES (188, 'Super Cup', 'Portugal');
INSERT INTO public.league VALUES (535, 'Qatar Stars League', 'Qatar');
INSERT INTO public.league VALUES (9661, 'Qualification', 'Qatar');
INSERT INTO public.league VALUES (189, 'Liga I', 'Romania');
INSERT INTO public.league VALUES (9113, 'Liga II', 'Romania');
INSERT INTO public.league VALUES (190, 'Cupa României', 'Romania');
INSERT INTO public.league VALUES (192, 'Super Cup', 'Romania');
INSERT INTO public.league VALUES (9587, 'Liga I Qualification', 'Romania');
INSERT INTO public.league VALUES (63, 'Premier League', 'Russia');
INSERT INTO public.league VALUES (193, 'Russian Cup', 'Russia');
INSERT INTO public.league VALUES (9333, 'Premier League Qualification', 'Russia');
INSERT INTO public.league VALUES (195, 'Super Cup', 'Russia');
INSERT INTO public.league VALUES (338, '1. Division', 'Russia');
INSERT INTO public.league VALUES (9123, 'Second League', 'Russia');
INSERT INTO public.league VALUES (536, 'Saudi Pro League', 'Saudi Arabia');
INSERT INTO public.league VALUES (9942, 'King''s Cup', 'Saudi Arabia');
INSERT INTO public.league VALUES (10074, 'Super Cup', 'Saudi Arabia');
INSERT INTO public.league VALUES (64, 'Premiership', 'Scotland');
INSERT INTO public.league VALUES (123, 'Championship', 'Scotland');
INSERT INTO public.league VALUES (124, 'League One', 'Scotland');
INSERT INTO public.league VALUES (125, 'League Two', 'Scotland');
INSERT INTO public.league VALUES (181, 'Premiership playoff', 'Scotland');
INSERT INTO public.league VALUES (179, 'Challenge Cup', 'Scotland');
INSERT INTO public.league VALUES (9737, 'Championship playoff', 'Scotland');
INSERT INTO public.league VALUES (180, 'League Cup', 'Scotland');
INSERT INTO public.league VALUES (9738, 'League One Playoff', 'Scotland');
INSERT INTO public.league VALUES (9739, 'League Two Playoff', 'Scotland');
INSERT INTO public.league VALUES (137, 'Scottish Cup', 'Scotland');
INSERT INTO public.league VALUES (182, 'Super Liga', 'Serbia');
INSERT INTO public.league VALUES (183, 'Kup Srbije', 'Serbia');
INSERT INTO public.league VALUES (10583, 'Super Liga Qualification', 'Serbia');
INSERT INTO public.league VALUES (461, 'Singapore Premier League', 'Singapore');
INSERT INTO public.league VALUES (9143, 'Singapore Cup', 'Singapore');
INSERT INTO public.league VALUES (176, '1. liga', 'Slovakia');
INSERT INTO public.league VALUES (8973, '2. Liga', 'Slovakia');
INSERT INTO public.league VALUES (177, 'FA Cup', 'Slovakia');
INSERT INTO public.league VALUES (9845, 'Super Liga Qualification', 'Slovakia');
INSERT INTO public.league VALUES (173, 'Prva Liga', 'Slovenia');
INSERT INTO public.league VALUES (492, 'Prva Liga Qualification', 'Slovenia');
INSERT INTO public.league VALUES (174, 'Slovenia Cup', 'Slovenia');
INSERT INTO public.league VALUES (10708, 'Knockout Cup', 'South Africa');
INSERT INTO public.league VALUES (9474, 'MTN8', 'South Africa');
INSERT INTO public.league VALUES (9473, 'Nedbank Cup', 'South Africa');
INSERT INTO public.league VALUES (537, 'Premier Soccer League', 'South Africa');
INSERT INTO public.league VALUES (10584, 'South Africa League Qualification', 'South Africa');
INSERT INTO public.league VALUES (9080, 'K League 1', 'South Korea');
INSERT INTO public.league VALUES (9422, 'K League Qualification', 'South Korea');
INSERT INTO public.league VALUES (9551, 'Cup', 'South Korea');
INSERT INTO public.league VALUES (9116, 'K League 2', 'South Korea');
INSERT INTO public.league VALUES (87, 'LaLiga', 'Spain');
INSERT INTO public.league VALUES (140, 'LaLiga2', 'Spain');
INSERT INTO public.league VALUES (8968, 'Primera Federación', 'Spain');
INSERT INTO public.league VALUES (9138, 'Segunda Federación', 'Spain');
INSERT INTO public.league VALUES (9907, 'Liga F', 'Spain');
INSERT INTO public.league VALUES (138, 'Copa del Rey', 'Spain');
INSERT INTO public.league VALUES (139, 'Super Cup', 'Spain');
INSERT INTO public.league VALUES (10651, 'Copa de la Reina', 'Spain');
INSERT INTO public.league VALUES (67, 'Allsvenskan', 'Sweden');
INSERT INTO public.league VALUES (68, 'Allsvenskan Qualification', 'Sweden');
INSERT INTO public.league VALUES (168, 'Superettan', 'Sweden');
INSERT INTO public.league VALUES (172, 'Superettan Qualification', 'Sweden');
INSERT INTO public.league VALUES (9089, 'Damallsvenskan (W)', 'Sweden');
INSERT INTO public.league VALUES (171, 'Svenska Cupen', 'Sweden');
INSERT INTO public.league VALUES (9634, '1. Division Qualification', 'Sweden');
INSERT INTO public.league VALUES (10316, 'Damallsvenskan Qualification (W)', 'Sweden');
INSERT INTO public.league VALUES (10308, 'Eliteettan (W)', 'Sweden');
INSERT INTO public.league VALUES (169, 'Ettan', 'Sweden');
INSERT INTO public.league VALUES (69, 'Super League', 'Switzerland');
INSERT INTO public.league VALUES (163, 'Challenge League', 'Switzerland');
INSERT INTO public.league VALUES (10433, 'Challenge League Qualification', 'Switzerland');
INSERT INTO public.league VALUES (70, 'Super League Qualification', 'Switzerland');
INSERT INTO public.league VALUES (164, 'Swiss Cup', 'Switzerland');
INSERT INTO public.league VALUES (9066, 'Premier League', 'Tanzania');
INSERT INTO public.league VALUES (10028, 'Premier League Qualification', 'Tanzania');
INSERT INTO public.league VALUES (8984, 'Premier League', 'Thailand');
INSERT INTO public.league VALUES (544, 'Ligue I', 'Tunisia');
INSERT INTO public.league VALUES (9669, 'Ligue I Qualification', 'Tunisia');
INSERT INTO public.league VALUES (71, 'Süper Lig', 'Turkiye');
INSERT INTO public.league VALUES (165, '1. Lig', 'Turkiye');
INSERT INTO public.league VALUES (166, 'Super Cup', 'Turkiye');
INSERT INTO public.league VALUES (151, 'Turkish Cup', 'Turkiye');
INSERT INTO public.league VALUES (441, 'Premier League', 'Ukraine');
INSERT INTO public.league VALUES (9829, 'Premier League Qualification', 'Ukraine');
INSERT INTO public.league VALUES (10023, '1. Division Qualification', 'Ukraine');
INSERT INTO public.league VALUES (442, 'Ukraine Cup', 'Ukraine');
INSERT INTO public.league VALUES (538, 'Arabian Gulf League', 'United Arab Emirates');
INSERT INTO public.league VALUES (9943, 'Cup', 'United Arab Emirates');
INSERT INTO public.league VALUES (130, 'MLS', 'United States');
INSERT INTO public.league VALUES (8972, 'USL Championship', 'United States');
INSERT INTO public.league VALUES (9296, 'USL League One', 'United States');
INSERT INTO public.league VALUES (9441, 'Open Cup', 'United States');
INSERT INTO public.league VALUES (9134, 'NWSL', 'United States');
INSERT INTO public.league VALUES (10282, 'MLS Next Pro', 'United States');
INSERT INTO public.league VALUES (10084, 'NISA', 'United States');
INSERT INTO public.league VALUES (10167, 'NWSL Challenge Cup', 'United States');
INSERT INTO public.league VALUES (10654, 'USL Jägermeister Cup', 'United States');
INSERT INTO public.league VALUES (10699, 'USL Super League Women', 'United States');
INSERT INTO public.league VALUES (10342, 'Copa Uruguay', 'Uruguay');
INSERT INTO public.league VALUES (161, 'Primera Division', 'Uruguay');
INSERT INTO public.league VALUES (9122, 'Segunda Division', 'Uruguay');
INSERT INTO public.league VALUES (10193, 'Segunda Division Qualification', 'Uruguay');
INSERT INTO public.league VALUES (10343, 'Supercopa', 'Uruguay');
INSERT INTO public.league VALUES (339, 'Primera Division', 'Venezuela');
INSERT INTO public.league VALUES (9088, 'V-League', 'Vietnam');
INSERT INTO public.league VALUES (9628, 'V-League Qualification', 'Vietnam');
INSERT INTO public.league VALUES (116, 'Premier League', 'Wales');
INSERT INTO public.league VALUES (9166, 'Welsh Cup', 'Wales');
INSERT INTO public.league VALUES (4, 'Euro Championship', 'World');
INSERT INTO public.league VALUES (1, 'World Cup', 'World');
INSERT INTO public.league VALUES (2, 'UEFA Champions League', 'World');
INSERT INTO public.league VALUES (3, 'UEFA Europa League', 'World');
INSERT INTO public.league VALUES (5, 'UEFA Nations League', 'World');
INSERT INTO public.league VALUES (21, 'Confederations Cup', 'World');
INSERT INTO public.league VALUES (39, 'Premier League', 'England');
INSERT INTO public.league VALUES (78, 'Bundesliga', 'Germany');
INSERT INTO public.league VALUES (88, 'Eredivisie', 'Netherlands');
INSERT INTO public.league VALUES (94, 'Primeira Liga', 'Portugal');
INSERT INTO public.league VALUES (62, 'Ligue 2', 'France');
INSERT INTO public.league VALUES (311, '1st Division', 'Albania');
INSERT INTO public.league VALUES (310, 'Superliga', 'Albania');
INSERT INTO public.league VALUES (334, 'Persha Liga', 'Ukraine');
INSERT INTO public.league VALUES (301, 'Pro League', 'United-Arab-Emirates');
INSERT INTO public.league VALUES (303, 'Division 1', 'United-Arab-Emirates');
INSERT INTO public.league VALUES (302, 'League Cup', 'United-Arab-Emirates');
INSERT INTO public.league VALUES (269, 'Segunda División', 'Uruguay');
INSERT INTO public.league VALUES (202, 'Ligue 1', 'Tunisia');
INSERT INTO public.league VALUES (66, 'Coupe de France', 'France');
INSERT INTO public.league VALUES (65, 'Coupe de la Ligue', 'France');
INSERT INTO public.league VALUES (233, 'Premier League', 'Egypt');
INSERT INTO public.league VALUES (370, 'Primera Division', 'El-Salvador');
INSERT INTO public.league VALUES (328, 'Esiliiga A', 'Estonia');
INSERT INTO public.league VALUES (329, 'Meistriliiga', 'Estonia');
INSERT INTO public.league VALUES (326, 'Erovnuli Liga 2', 'Georgia');
INSERT INTO public.league VALUES (377, 'Division d''Honneur', 'Guadeloupe');
INSERT INTO public.league VALUES (79, '2. Bundesliga', 'Germany');
INSERT INTO public.league VALUES (80, '3. Liga', 'Germany');
INSERT INTO public.league VALUES (81, 'DFB Pokal', 'Germany');
INSERT INTO public.league VALUES (7, 'Asian Cup', 'World');
INSERT INTO public.league VALUES (8, 'World Cup - Women', 'World');
INSERT INTO public.league VALUES (312, '1a Divisió', 'Andorra');
INSERT INTO public.league VALUES (313, '2a Divisió', 'Andorra');
INSERT INTO public.league VALUES (191, 'Brisbane Premier League', 'Australia');
INSERT INTO public.league VALUES (220, 'Cup', 'Austria');
INSERT INTO public.league VALUES (418, 'Birinci Dasta', 'Azerbaidjan');
INSERT INTO public.league VALUES (419, 'Premyer Liqa', 'Azerbaidjan');
INSERT INTO public.league VALUES (299, 'Primera División', 'Venezuela');
INSERT INTO public.league VALUES (300, 'Segunda División', 'Venezuela');
INSERT INTO public.league VALUES (406, 'Professional League', 'Oman');
INSERT INTO public.league VALUES (322, 'Premier League', 'Jamaica');
INSERT INTO public.league VALUES (387, 'League', 'Jordan');
INSERT INTO public.league VALUES (388, '1. Division', 'Kazakhstan');
INSERT INTO public.league VALUES (234, 'Liga Nacional', 'Honduras');
INSERT INTO public.league VALUES (381, 'HKFA 1st Division', 'Hong-Kong');
INSERT INTO public.league VALUES (380, 'Premier League', 'Hong-Kong');
INSERT INTO public.league VALUES (390, 'Premier League', 'Lebanon');
INSERT INTO public.league VALUES (261, 'National Division', 'Luxembourg');
INSERT INTO public.league VALUES (306, 'Second Division', 'Qatar');
INSERT INTO public.league VALUES (305, 'Stars League', 'Qatar');
INSERT INTO public.league VALUES (45, 'FA Cup', 'England');
INSERT INTO public.league VALUES (43, 'National League', 'England');
INSERT INTO public.league VALUES (42, 'League Two', 'England');
INSERT INTO public.league VALUES (15, 'FIFA Intercontinental Cup', 'World');
INSERT INTO public.league VALUES (422, 'Premier League', 'Barbados');
INSERT INTO public.league VALUES (480, 'Olympics Men', 'World');
INSERT INTO public.league VALUES (72, 'Serie B', 'Brazil');
INSERT INTO public.league VALUES (75, 'Serie C', 'Brazil');
INSERT INTO public.league VALUES (76, 'Serie D', 'Brazil');
INSERT INTO public.league VALUES (257, 'US Open Cup', 'USA');
INSERT INTO public.league VALUES (369, 'Super League', 'Uzbekistan');
INSERT INTO public.league VALUES (296, 'Thai League 1', 'Thailand');
INSERT INTO public.league VALUES (297, 'Thai League 2', 'Thailand');
INSERT INTO public.league VALUES (366, '1. Deild', 'Faroe-Islands');
INSERT INTO public.league VALUES (367, 'Meistaradeildin', 'Faroe-Islands');
INSERT INTO public.league VALUES (245, 'Ykkönen', 'Finland');
INSERT INTO public.league VALUES (244, 'Veikkausliiga', 'Finland');
INSERT INTO public.league VALUES (243, 'Liga Pro Serie B', 'Ecuador');
INSERT INTO public.league VALUES (397, 'Girabola', 'Angola');
INSERT INTO public.league VALUES (343, 'First League', 'Armenia');
INSERT INTO public.league VALUES (481, 'Northern NSW NPL', 'Australia');
INSERT INTO public.league VALUES (400, 'Super League', 'Zambia');
INSERT INTO public.league VALUES (340, 'V.League 1', 'Vietnam');
INSERT INTO public.league VALUES (102, 'Emperor Cup', 'Japan');
INSERT INTO public.league VALUES (101, 'J-League Cup', 'Japan');
INSERT INTO public.league VALUES (98, 'J1 League', 'Japan');
INSERT INTO public.league VALUES (99, 'J2 League', 'Japan');
INSERT INTO public.league VALUES (100, 'J3 League', 'Japan');
INSERT INTO public.league VALUES (389, 'Premier League', 'Kazakhstan');
INSERT INTO public.league VALUES (379, 'Ligue Haïtienne', 'Haiti');
INSERT INTO public.league VALUES (364, '1. Liga', 'Latvia');
INSERT INTO public.league VALUES (365, 'Virsliga', 'Latvia');
INSERT INTO public.league VALUES (361, '1 Lyga', 'Lithuania');
INSERT INTO public.league VALUES (362, 'A Lyga', 'Lithuania');
INSERT INTO public.league VALUES (28, 'SAFF Championship', 'World');
INSERT INTO public.league VALUES (421, 'Division di Honor', 'Aruba');
INSERT INTO public.league VALUES (420, 'Cup', 'Azerbaidjan');
INSERT INTO public.league VALUES (298, 'FA Cup', 'Thailand');
INSERT INTO public.league VALUES (376, 'National Football League', 'Fiji');
INSERT INTO public.league VALUES (327, 'Erovnuli Liga', 'Georgia');
INSERT INTO public.league VALUES (378, 'Ligue 1', 'Guinea');
INSERT INTO public.league VALUES (37, 'World Cup - Qualification Intercontinental Play-offs', 'World');
INSERT INTO public.league VALUES (19, 'African Nations Championship', 'World');
INSERT INTO public.league VALUES (24, 'AFF Championship', 'World');
INSERT INTO public.league VALUES (184, 'League Two', 'Scotland');
INSERT INTO public.league VALUES (22, 'CONCACAF Gold Cup', 'World');
INSERT INTO public.league VALUES (23, 'EAFF E-1 Football Championship', 'World');
INSERT INTO public.league VALUES (27, 'OFC Champions League', 'World');
INSERT INTO public.league VALUES (6, 'Africa Cup of Nations', 'World');
INSERT INTO public.league VALUES (9, 'Copa America', 'World');
INSERT INTO public.league VALUES (255, 'USL Championship', 'USA');
INSERT INTO public.league VALUES (363, 'Premier League', 'Ethiopia');
INSERT INTO public.league VALUES (497, 'Japan Football League', 'Japan');
INSERT INTO public.league VALUES (317, '1st League - RS', 'Bosnia');
INSERT INTO public.league VALUES (316, '1st League - FBiH', 'Bosnia');
INSERT INTO public.league VALUES (295, 'K3 League', 'South-Korea');
INSERT INTO public.league VALUES (495, 'Hazfi Cup', 'Iran');
INSERT INTO public.league VALUES (496, 'Liga Alef', 'Israel');
INSERT INTO public.league VALUES (368, 'Premier League', 'Singapore');
INSERT INTO public.league VALUES (314, 'Cup', 'Bosnia');
INSERT INTO public.league VALUES (315, 'Premijer Liga', 'Bosnia');
INSERT INTO public.league VALUES (371, 'First League', 'Macedonia');
INSERT INTO public.league VALUES (382, 'Liga Leumit', 'Israel');
INSERT INTO public.league VALUES (383, 'Ligat Ha''al', 'Israel');
INSERT INTO public.league VALUES (386, 'Ligue 1', 'Ivory-Coast');
INSERT INTO public.league VALUES (392, 'Challenge League', 'Malta');
INSERT INTO public.league VALUES (393, 'Premier League', 'Malta');
INSERT INTO public.league VALUES (394, 'Super Liga', 'Moldova');
INSERT INTO public.league VALUES (396, 'Primera Division', 'Nicaragua');
INSERT INTO public.league VALUES (96, 'Taça de Portugal', 'Portugal');
INSERT INTO public.league VALUES (399, 'NPFL', 'Nigeria');
INSERT INTO public.league VALUES (401, 'Premier Soccer League', 'Zimbabwe');
INSERT INTO public.league VALUES (402, 'Sudani Premier League', 'Sudan');
INSERT INTO public.league VALUES (403, 'Ligue 1', 'Senegal');
INSERT INTO public.league VALUES (404, 'Campionato', 'San-Marino');
INSERT INTO public.league VALUES (411, 'Elite One', 'Cameroon');
INSERT INTO public.league VALUES (410, 'C-League', 'Cambodia');
INSERT INTO public.league VALUES (417, 'Premier League', 'Bahrain');
INSERT INTO public.league VALUES (415, 'Championnat National', 'Benin');
INSERT INTO public.league VALUES (414, 'Premier League', 'Bermuda');
INSERT INTO public.league VALUES (413, 'Super League', 'Bhutan');
INSERT INTO public.league VALUES (412, 'Premier League', 'Botswana');
INSERT INTO public.league VALUES (398, 'Premier League', 'Bangladesh');
INSERT INTO public.league VALUES (16, 'CONCACAF Champions League', 'World');
INSERT INTO public.league VALUES (17, 'AFC Champions League', 'World');
INSERT INTO public.league VALUES (25, 'Gulf Cup of Nations', 'World');
INSERT INTO public.league VALUES (26, 'International Champions Cup', 'World');
INSERT INTO public.league VALUES (103, 'Eliteserien', 'Norway');
INSERT INTO public.league VALUES (89, 'Eerste Divisie', 'Netherlands');
INSERT INTO public.league VALUES (95, 'Segunda Liga', 'Portugal');
INSERT INTO public.league VALUES (162, 'Primera División', 'Costa-Rica');
INSERT INTO public.league VALUES (210, 'HNL', 'Croatia');
INSERT INTO public.league VALUES (73, 'Copa Do Brasil', 'Brazil');
INSERT INTO public.league VALUES (90, 'KNVB Beker', 'Netherlands');
INSERT INTO public.league VALUES (170, 'League One', 'China');
INSERT INTO public.league VALUES (211, 'First NL', 'Croatia');
INSERT INTO public.league VALUES (74, 'Brasileiro Women', 'Brazil');
INSERT INTO public.league VALUES (44, 'FA WSL', 'England');
INSERT INTO public.league VALUES (82, 'Frauen Bundesliga', 'Germany');
INSERT INTO public.league VALUES (91, 'Eredivisie Women', 'Netherlands');
INSERT INTO public.league VALUES (236, 'First League', 'Russia');
INSERT INTO public.league VALUES (104, '1. Division', 'Norway');
INSERT INTO public.league VALUES (114, 'Superettan', 'Sweden');
INSERT INTO public.league VALUES (259, 'Canadian Championship', 'Canada');
INSERT INTO public.league VALUES (279, 'Premier League', 'Malaysia');
INSERT INTO public.league VALUES (280, 'Premiership', 'New-Zealand');
INSERT INTO public.league VALUES (281, 'Primera División', 'Peru');
INSERT INTO public.league VALUES (282, 'Segunda División', 'Peru');
INSERT INTO public.league VALUES (283, 'Liga I', 'Romania');
INSERT INTO public.league VALUES (284, 'Liga II', 'Romania');
INSERT INTO public.league VALUES (286, 'Super Liga', 'Serbia');
INSERT INTO public.league VALUES (287, 'Prva Liga', 'Serbia');
INSERT INTO public.league VALUES (288, 'Premier Soccer League', 'South-Africa');
INSERT INTO public.league VALUES (289, '1st Division', 'South-Africa');
INSERT INTO public.league VALUES (290, 'Persian Gulf Pro League', 'Iran');
INSERT INTO public.league VALUES (291, 'Azadegan League', 'Iran');
INSERT INTO public.league VALUES (292, 'K League 1', 'South-Korea');
INSERT INTO public.league VALUES (293, 'K League 2', 'South-Korea');
INSERT INTO public.league VALUES (307, 'Pro League', 'Saudi-Arabia');
INSERT INTO public.league VALUES (308, 'Division 1', 'Saudi-Arabia');
INSERT INTO public.league VALUES (309, 'Division 2', 'Saudi-Arabia');
INSERT INTO public.league VALUES (488, 'U19 Bundesliga', 'Germany');
INSERT INTO public.league VALUES (372, 'Second League', 'Macedonia');
INSERT INTO public.league VALUES (10, 'Friendlies', 'World');
INSERT INTO public.league VALUES (14, 'UEFA Youth League', 'World');
INSERT INTO public.league VALUES (18, 'AFC Cup', 'World');
INSERT INTO public.league VALUES (20, 'CAF Confederation Cup', 'World');
INSERT INTO public.league VALUES (407, 'Championship', 'Northern-Ireland');
INSERT INTO public.league VALUES (408, 'Premiership', 'Northern-Ireland');
INSERT INTO public.league VALUES (425, 'Premier League', 'Syria');
INSERT INTO public.league VALUES (77, 'Alagoano', 'Brazil');
INSERT INTO public.league VALUES (490, 'World Cup - U20', 'World');
INSERT INTO public.league VALUES (498, 'Cup', 'Kazakhstan');
INSERT INTO public.league VALUES (258, 'Canadian Soccer League', 'Canada');
INSERT INTO public.league VALUES (304, 'Liga Panameña de Fútbol', 'Panama');
INSERT INTO public.league VALUES (106, 'Ekstraklasa', 'Poland');
INSERT INTO public.league VALUES (265, 'Primera División', 'Chile');
INSERT INTO public.league VALUES (277, 'Super League', 'Kenya');
INSERT INTO public.league VALUES (318, '1. Division', 'Cyprus');
INSERT INTO public.league VALUES (319, '2. Division', 'Cyprus');
INSERT INTO public.league VALUES (320, '3. Division', 'Cyprus');
INSERT INTO public.league VALUES (201, 'Botola 2', 'Morocco');
INSERT INTO public.league VALUES (323, 'Indian Super League', 'India');
INSERT INTO public.league VALUES (324, 'I-League', 'India');
INSERT INTO public.league VALUES (107, 'I Liga', 'Poland');
INSERT INTO public.league VALUES (345, 'Czech Liga', 'Czech-Republic');
INSERT INTO public.league VALUES (346, 'FNL', 'Czech-Republic');
INSERT INTO public.league VALUES (355, 'First League', 'Montenegro');
INSERT INTO public.league VALUES (356, 'Second League', 'Montenegro');
INSERT INTO public.league VALUES (344, 'Primera División', 'Bolivia');
INSERT INTO public.league VALUES (373, '1. SNL', 'Slovenia');
INSERT INTO public.league VALUES (374, '2. SNL', 'Slovenia');
INSERT INTO public.league VALUES (391, 'Super League', 'Malawi');
INSERT INTO public.league VALUES (405, 'National Soccer League', 'Rwanda');
INSERT INTO public.league VALUES (409, 'Premier League', 'Namibia');
INSERT INTO public.league VALUES (416, 'Premier League', 'Belize');
INSERT INTO public.league VALUES (384, 'State Cup', 'Israel');
INSERT INTO public.league VALUES (285, 'Cupa României', 'Romania');
INSERT INTO public.league VALUES (321, 'Cup', 'Cyprus');
INSERT INTO public.league VALUES (31, 'World Cup - Qualification CONCACAF', 'World');
INSERT INTO public.league VALUES (32, 'World Cup - Qualification Europe', 'World');
INSERT INTO public.league VALUES (33, 'World Cup - Qualification Oceania', 'World');
INSERT INTO public.league VALUES (34, 'World Cup - Qualification South America', 'World');
INSERT INTO public.league VALUES (29, 'World Cup - Qualification Africa', 'World');
INSERT INTO public.league VALUES (30, 'World Cup - Qualification Asia', 'World');
INSERT INTO public.league VALUES (150, 'Second Amateur Division - VFV B', 'Belgium');
INSERT INTO public.league VALUES (152, 'Third Amateur Division - VFV B', 'Belgium');
INSERT INTO public.league VALUES (175, 'Third League - Northeast', 'Bulgaria');
INSERT INTO public.league VALUES (178, 'Third League - Southwest', 'Bulgaria');
INSERT INTO public.league VALUES (49, 'National League - Play-offs', 'England');
INSERT INTO public.league VALUES (491, 'Løgmanssteypid', 'Faroe-Islands');
INSERT INTO public.league VALUES (493, 'UEFA U19 Championship', 'World');
INSERT INTO public.league VALUES (499, 'Malaysia Cup', 'Malaysia');
INSERT INTO public.league VALUES (227, 'Landesliga - Oberosterreich', 'Austria');
INSERT INTO public.league VALUES (148, 'Second Amateur Division - ACFF', 'Belgium');
INSERT INTO public.league VALUES (153, 'Provincial - Antwerpen', 'Belgium');
INSERT INTO public.league VALUES (154, 'Provincial - Brabant VFV', 'Belgium');
INSERT INTO public.league VALUES (155, 'Provincial - Hainaut', 'Belgium');
INSERT INTO public.league VALUES (156, 'Provincial - Liege', 'Belgium');
INSERT INTO public.league VALUES (157, 'Provincial - Limburg', 'Belgium');
INSERT INTO public.league VALUES (158, 'Provincial - Luxembourg', 'Belgium');
INSERT INTO public.league VALUES (159, 'Provincial - Namur', 'Belgium');
INSERT INTO public.league VALUES (160, 'Provincial - Oost-Vlaanderen', 'Belgium');
INSERT INTO public.league VALUES (423, 'Ligue 1', 'Burkina-Faso');
INSERT INTO public.league VALUES (424, 'Ligue 1', 'Congo-DR');
INSERT INTO public.league VALUES (214, 'Third NL - Jug', 'Croatia');
INSERT INTO public.league VALUES (348, '3. liga - CFL A', 'Czech-Republic');
INSERT INTO public.league VALUES (349, '3. liga - MSFL', 'Czech-Republic');
INSERT INTO public.league VALUES (350, '4. liga - Divizie A', 'Czech-Republic');
INSERT INTO public.league VALUES (351, '4. liga - Divizie B', 'Czech-Republic');
INSERT INTO public.league VALUES (352, '4. liga - Divizie C', 'Czech-Republic');
INSERT INTO public.league VALUES (353, '4. liga - Divizie D', 'Czech-Republic');
INSERT INTO public.league VALUES (354, '4. liga - Divizie E', 'Czech-Republic');
INSERT INTO public.league VALUES (50, 'National League - North', 'England');
INSERT INTO public.league VALUES (56, 'Non League Div One - Southern South', 'England');
INSERT INTO public.league VALUES (92, 'Derde Divisie - Saturday', 'Netherlands');
INSERT INTO public.league VALUES (93, 'Derde Divisie - Sunday', 'Netherlands');
INSERT INTO public.league VALUES (341, 'Cup', 'Vietnam');
INSERT INTO public.league VALUES (238, 'Youth Championship', 'Russia');
INSERT INTO public.league VALUES (83, 'Regionalliga - Bayern', 'Germany');
INSERT INTO public.league VALUES (84, 'Regionalliga - Nord', 'Germany');
INSERT INTO public.league VALUES (426, 'Serie D - Girone A', 'Italy');
INSERT INTO public.league VALUES (427, 'Serie D - Girone B', 'Italy');
INSERT INTO public.league VALUES (428, 'Serie D - Girone C', 'Italy');
INSERT INTO public.league VALUES (429, 'Serie D - Girone D', 'Italy');
INSERT INTO public.league VALUES (430, 'Serie D - Girone E', 'Italy');
INSERT INTO public.league VALUES (431, 'Serie D - Girone F', 'Italy');
INSERT INTO public.league VALUES (432, 'Serie D - Girone G', 'Italy');
INSERT INTO public.league VALUES (433, 'Serie D - Girone H', 'Italy');
INSERT INTO public.league VALUES (434, 'Serie D - Girone I', 'Italy');
INSERT INTO public.league VALUES (435, 'Primera División RFEF - Group 1', 'Spain');
INSERT INTO public.league VALUES (436, 'Primera División RFEF - Group 2', 'Spain');
INSERT INTO public.league VALUES (437, 'Primera División RFEF - Group 3', 'Spain');
INSERT INTO public.league VALUES (438, 'Primera División RFEF - Group 4', 'Spain');
INSERT INTO public.league VALUES (443, 'Tercera División RFEF - Group 5', 'Spain');
INSERT INTO public.league VALUES (444, 'Tercera División RFEF - Group 6', 'Spain');
INSERT INTO public.league VALUES (445, 'Tercera División RFEF - Group 7', 'Spain');
INSERT INTO public.league VALUES (446, 'Tercera División RFEF - Group 8', 'Spain');
INSERT INTO public.league VALUES (447, 'Tercera División RFEF - Group 9', 'Spain');
INSERT INTO public.league VALUES (448, 'Tercera División RFEF - Group 10', 'Spain');
INSERT INTO public.league VALUES (449, 'Tercera División RFEF - Group 11', 'Spain');
INSERT INTO public.league VALUES (450, 'Tercera División RFEF - Group 12', 'Spain');
INSERT INTO public.league VALUES (451, 'Tercera División RFEF - Group 13', 'Spain');
INSERT INTO public.league VALUES (452, 'Tercera División RFEF - Group 14', 'Spain');
INSERT INTO public.league VALUES (453, 'Tercera División RFEF - Group 15', 'Spain');
INSERT INTO public.league VALUES (454, 'Tercera División RFEF - Group 16', 'Spain');
INSERT INTO public.league VALUES (455, 'Tercera División RFEF - Group 17', 'Spain');
INSERT INTO public.league VALUES (456, 'Tercera División RFEF - Group 18', 'Spain');
INSERT INTO public.league VALUES (457, 'Campeonato de Portugal Prio - Group A', 'Portugal');
INSERT INTO public.league VALUES (458, 'Campeonato de Portugal Prio - Group B', 'Portugal');
INSERT INTO public.league VALUES (459, 'Campeonato de Portugal Prio - Group C', 'Portugal');
INSERT INTO public.league VALUES (460, 'Campeonato de Portugal Prio - Group D', 'Portugal');
INSERT INTO public.league VALUES (462, 'National 3 - Group B', 'France');
INSERT INTO public.league VALUES (463, 'National 3 - Group C', 'France');
INSERT INTO public.league VALUES (464, 'National 3 - Group D', 'France');
INSERT INTO public.league VALUES (465, 'National 3 - Group E', 'France');
INSERT INTO public.league VALUES (466, 'National 3 - Group F', 'France');
INSERT INTO public.league VALUES (467, 'National 3 - Group H', 'France');
INSERT INTO public.league VALUES (468, 'National 3 - Group I', 'France');
INSERT INTO public.league VALUES (469, 'National 3 - Group J', 'France');
INSERT INTO public.league VALUES (470, 'National 3 - Group K', 'France');
INSERT INTO public.league VALUES (471, 'National 3 - Group L', 'France');
INSERT INTO public.league VALUES (472, 'National 3 - Group M', 'France');
INSERT INTO public.league VALUES (473, '2. Division - Group 1', 'Norway');
INSERT INTO public.league VALUES (474, '2. Division - Group 2', 'Norway');
INSERT INTO public.league VALUES (484, 'Frauenliga', 'Austria');
INSERT INTO public.league VALUES (485, 'Federation Cup', 'Bahrain');
INSERT INTO public.league VALUES (486, 'Coppa', 'Belarus');
INSERT INTO public.league VALUES (487, 'First Amateur Division', 'Belgium');
INSERT INTO public.league VALUES (489, 'USL League One', 'USA');
INSERT INTO public.league VALUES (494, 'Super League 2', 'Greece');
INSERT INTO public.league VALUES (395, 'Liga 1', 'Moldova');
INSERT INTO public.league VALUES (167, 'Cup', 'Iceland');
INSERT INTO public.league VALUES (359, 'FAI Cup', 'Ireland');
INSERT INTO public.league VALUES (360, 'League Cup', 'Ireland');
INSERT INTO public.league VALUES (385, 'Toto Cup Ligat Al', 'Israel');
INSERT INTO public.league VALUES (11, 'CONMEBOL Sudamericana', 'World');
INSERT INTO public.league VALUES (12, 'CAF Champions League', 'World');
INSERT INTO public.league VALUES (13, 'CONMEBOL Libertadores', 'World');
INSERT INTO public.league VALUES (115, 'Svenska Cupen', 'Sweden');
INSERT INTO public.league VALUES (375, 'Cup', 'Slovenia');
INSERT INTO public.league VALUES (97, 'Taça da Liga', 'Portugal');
INSERT INTO public.league VALUES (105, 'NM Cupen', 'Norway');
INSERT INTO public.league VALUES (294, 'FA Cup', 'South-Korea');
INSERT INTO public.league VALUES (325, 'Santosh Trophy', 'India');
INSERT INTO public.league VALUES (347, 'Cup', 'Czech-Republic');
INSERT INTO public.league VALUES (35, 'Asian Cup - Qualification', 'World');
INSERT INTO public.league VALUES (194, 'South Australia NPL', 'Australia');
INSERT INTO public.league VALUES (357, 'Premier Division', 'Ireland');
INSERT INTO public.league VALUES (358, 'First Division', 'Ireland');
INSERT INTO public.league VALUES (482, 'Queensland NPL', 'Australia');
INSERT INTO public.league VALUES (475, 'Paulista - A1', 'Brazil');
INSERT INTO public.league VALUES (476, 'Paulista - A2', 'Brazil');
INSERT INTO public.league VALUES (477, 'Gaúcho - 1', 'Brazil');
INSERT INTO public.league VALUES (478, 'Gaúcho - 2', 'Brazil');
INSERT INTO public.league VALUES (479, 'Canadian Premier League', 'Canada');
INSERT INTO public.league VALUES (483, 'Copa de la Superliga', 'Argentina');
INSERT INTO public.league VALUES (500, 'FA Cup', 'Malaysia');
INSERT INTO public.league VALUES (36, 'Africa Cup of Nations - Qualification', 'World');
